import { useState } from "react";
import { useNavigate } from "@/lib/router-compat";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Loader2, Shield } from "lucide-react";
import { useToast } from "@/hooks/use-toast";

const termsContent = [
  { title: "1. Acceptance of Terms", body: "By accessing or using Startup Jury AI, you agree to be bound by these Terms and Conditions. If you do not agree, you may not use the service." },
  { title: "2. Description of Service", body: "Startup Jury AI provides AI-powered startup idea evaluation through simulated expert panel debates. The service generates opinions using artificial intelligence and does not constitute professional investment, legal, or business advice." },
  { title: "3. User Accounts", body: "You are responsible for maintaining the confidentiality of your account credentials. You agree to provide accurate information during registration and to notify us immediately of any unauthorized use of your account." },
  { title: "4. Acceptable Use", body: "You agree not to use the service to submit content that is unlawful, harmful, threatening, abusive, or otherwise objectionable. You may not attempt to interfere with the proper functioning of the service." },
  { title: "5. Intellectual Property", body: "All content generated by the AI personas is provided for your personal use. You retain ownership of the ideas and content you submit. We retain ownership of the platform, AI models, and all related intellectual property." },
  { title: "6. Disclaimer of Warranties", body: 'The service is provided "as is" without warranties of any kind, express or implied. AI-generated evaluations are simulations and should not be relied upon as the sole basis for business decisions.' },
  { title: "7. Limitation of Liability", body: "In no event shall Startup Jury AI be liable for any indirect, incidental, special, consequential, or punitive damages arising out of your use of the service." },
  { title: "8. Privacy", body: "Your use of the service is also governed by our Privacy Policy. We collect and process data as described therein, including debate topics and session data to improve the service." },
  { title: "9. Modifications", body: "We reserve the right to modify these terms at any time. Continued use of the service after changes constitutes acceptance of the modified terms." },
  { title: "10. Contact", body: "If you have questions about these Terms, please reach out through the application." },
];

const privacyContent = [
  { title: "1. Information We Collect", body: "We collect information you provide directly, including your email address when you create an account, and the startup ideas and topics you submit for evaluation. We also collect usage data such as session history, debate interactions, and scoring results." },
  { title: "2. How We Use Your Information", body: "We use your information to provide and improve the Startup Jury AI service, including generating AI-powered evaluations, maintaining your session history, and personalizing your experience. We may also use aggregated, anonymized data for research and service improvement." },
  { title: "3. Data Storage and Security", body: "Your data is stored securely using industry-standard encryption and security practices. We retain your account data and session history for as long as your account is active. You may request deletion of your data at any time by contacting us." },
  { title: "4. Information Sharing", body: "We do not sell, trade, or rent your personal information to third parties. We may share anonymized, aggregated data for analytical purposes. We may disclose information if required by law or to protect our rights and safety." },
  { title: "5. Cookies and Tracking", body: "We use essential cookies to maintain your authentication session. We do not use third-party tracking or advertising cookies. You can manage cookie preferences through your browser settings." },
  { title: "6. Third-Party Services", body: "We use third-party AI models to generate debate responses and evaluations. The content you submit may be processed by these services. We do not share your personal identity with AI providers — only the content necessary for evaluation." },
  { title: "7. Your Rights", body: "You have the right to access, correct, or delete your personal data. You may export your session history or request complete account deletion. To exercise these rights, please contact us through the application." },
  { title: "8. Children's Privacy", body: "Startup Jury AI is not intended for use by individuals under the age of 13. We do not knowingly collect personal information from children." },
  { title: "9. Changes to This Policy", body: "We may update this Privacy Policy from time to time. We will notify you of any material changes by posting the new policy on this page with an updated revision date." },
  { title: "10. Contact", body: "If you have questions about this Privacy Policy, please reach out through the application." },
];

const AcceptTerms = () => {
  const [accepted, setAccepted] = useState(false);
  const [loading, setLoading] = useState(false);
  const navigate = useNavigate();
  const { toast } = useToast();

  const handleAccept = async () => {
    setLoading(true);
    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error("Not authenticated");

      const { error } = await supabase.from("user_agreements").insert({ user_id: user.id });
      if (error) throw error;

      navigate("/dashboard", { replace: true });
    } catch (err: any) {
      toast({ title: "Error", description: err.message, variant: "destructive" });
    } finally {
      setLoading(false);
    }
  };

  const renderSections = (sections: { title: string; body: string }[]) => (
    <div className="space-y-4 text-sm leading-relaxed">
      {sections.map((s) => (
        <div key={s.title}>
          <h3 className="font-semibold text-foreground mb-1">{s.title}</h3>
          <p className="text-muted-foreground">{s.body}</p>
        </div>
      ))}
    </div>
  );

  return (
    <div className="min-h-screen bg-background flex items-center justify-center px-4 py-6 sm:py-8">
      <div className="w-full max-w-2xl space-y-4 sm:space-y-6">
        <div className="text-center space-y-2">
          <div className="flex items-center justify-center gap-2">
            <Shield className="w-5 h-5 text-primary" />
            <h1 className="text-lg sm:text-xl font-semibold text-foreground tracking-tight">Review Our Policies</h1>
          </div>
          <p className="text-sm text-muted-foreground px-2">
            Please review and accept our Terms of Service and Privacy Policy to continue.
          </p>
        </div>

        <div className="rounded-lg border border-border bg-card p-4 sm:p-6 space-y-4 sm:space-y-5">
          <Tabs defaultValue="terms">
            <TabsList className="w-full">
              <TabsTrigger value="terms" className="flex-1">Terms of Service</TabsTrigger>
              <TabsTrigger value="privacy" className="flex-1">Privacy Policy</TabsTrigger>
            </TabsList>
            <TabsContent value="terms">
              <ScrollArea className="h-56 sm:h-72 rounded-md border border-border p-3 sm:p-4 mt-3">
                {renderSections(termsContent)}
              </ScrollArea>
            </TabsContent>
            <TabsContent value="privacy">
              <ScrollArea className="h-56 sm:h-72 rounded-md border border-border p-3 sm:p-4 mt-3">
                {renderSections(privacyContent)}
              </ScrollArea>
            </TabsContent>
          </Tabs>

          <label className="flex items-start gap-3 cursor-pointer">
            <Checkbox
              checked={accepted}
              onCheckedChange={(v) => setAccepted(v === true)}
              className="mt-0.5"
            />
            <span className="text-sm text-muted-foreground">
              I have read and agree to the <span className="text-foreground font-medium">Terms of Service</span> and{" "}
              <span className="text-foreground font-medium">Privacy Policy</span>.
            </span>
          </label>

          <Button
            onClick={handleAccept}
            disabled={!accepted || loading}
            className="w-full"
          >
            {loading && <Loader2 className="w-4 h-4 mr-2 animate-spin" />}
            Accept & Continue
          </Button>
        </div>
      </div>
    </div>
  );
};

export default AcceptTerms;
