import { useNavigate } from "react-router-dom";
import { ArrowLeft } from "lucide-react";
import { Button } from "@/components/ui/button";

const Terms = () => {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-background">
      <header className="border-b border-border px-6 py-4">
        <div className="max-w-3xl mx-auto flex items-center gap-3">
          <Button variant="ghost" size="icon" onClick={() => navigate("/")}>
            <ArrowLeft className="w-4 h-4" />
          </Button>
          <span className="text-lg font-semibold text-foreground tracking-tight">Terms & Conditions</span>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-6 py-12 prose prose-invert prose-sm">
        <h1 className="text-2xl font-bold text-foreground">Terms and Conditions</h1>
        <p className="text-muted-foreground text-sm">Last updated: February 22, 2026</p>

        <section className="space-y-4 mt-8 text-muted-foreground text-sm leading-relaxed">
          <h2 className="text-foreground text-base font-semibold">1. Acceptance of Terms</h2>
          <p>By accessing or using Startup Jury AI, you agree to be bound by these Terms and Conditions. If you do not agree, you may not use the service.</p>

          <h2 className="text-foreground text-base font-semibold">2. Description of Service</h2>
          <p>Startup Jury AI provides AI-powered startup idea evaluation through simulated expert panel debates. The service generates opinions using artificial intelligence and does not constitute professional investment, legal, or business advice.</p>

          <h2 className="text-foreground text-base font-semibold">3. User Accounts</h2>
          <p>You are responsible for maintaining the confidentiality of your account credentials. You agree to provide accurate information during registration and to notify us immediately of any unauthorized use of your account.</p>

          <h2 className="text-foreground text-base font-semibold">4. Acceptable Use</h2>
          <p>You agree not to use the service to submit content that is unlawful, harmful, threatening, abusive, or otherwise objectionable. You may not attempt to interfere with the proper functioning of the service.</p>

          <h2 className="text-foreground text-base font-semibold">5. Intellectual Property</h2>
          <p>All content generated by the AI personas is provided for your personal use. You retain ownership of the ideas and content you submit. We retain ownership of the platform, AI models, and all related intellectual property.</p>

          <h2 className="text-foreground text-base font-semibold">6. Disclaimer of Warranties</h2>
          <p>The service is provided "as is" without warranties of any kind, express or implied. AI-generated evaluations are simulations and should not be relied upon as the sole basis for business decisions.</p>

          <h2 className="text-foreground text-base font-semibold">7. Limitation of Liability</h2>
          <p>In no event shall Startup Jury AI be liable for any indirect, incidental, special, consequential, or punitive damages arising out of your use of the service.</p>

          <h2 className="text-foreground text-base font-semibold">8. Privacy</h2>
          <p>Your use of the service is also governed by our Privacy Policy. We collect and process data as described therein, including debate topics and session data to improve the service.</p>

          <h2 className="text-foreground text-base font-semibold">9. Modifications</h2>
          <p>We reserve the right to modify these terms at any time. Continued use of the service after changes constitutes acceptance of the modified terms.</p>

          <h2 className="text-foreground text-base font-semibold">10. Contact</h2>
          <p>If you have questions about these Terms, please visit our <button onClick={() => navigate("/auth")} className="text-primary hover:underline">Contact Us</button> page.</p>
        </section>
      </main>
    </div>
  );
};

export default Terms;
