/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AcceptTermsRouteImport } from './routes/accept-terms'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DebateRouteImport } from './routes/debate'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ApiDebateAiRouteImport } from './routes/api/debate-ai'
import { Route as ApiElevenlabsTtsRouteImport } from './routes/api/elevenlabs-tts'
import { Route as AppContactRouteImport } from './routes/app/contact'
import { Route as AppPrivacyRouteImport } from './routes/app/privacy'
import { Route as AppTermsRouteImport } from './routes/app/terms'
import { Route as ResultIdRouteImport } from './routes/result/$id'
import { Route as ApiHealthMetadataRouteImport } from './routes/api/health/metadata'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptTermsRoute = AcceptTermsRouteImport.update({
  id: '/accept-terms',
  path: '/accept-terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DebateRoute = DebateRouteImport.update({
  id: '/debate',
  path: '/debate',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebateAiRoute = ApiDebateAiRouteImport.update({
  id: '/api/debate-ai',
  path: '/api/debate-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiElevenlabsTtsRoute = ApiElevenlabsTtsRouteImport.update({
  id: '/api/elevenlabs-tts',
  path: '/api/elevenlabs-tts',
  getParentRoute: () => rootRouteImport,
} as any)
const AppContactRoute = AppContactRouteImport.update({
  id: '/app/contact',
  path: '/app/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPrivacyRoute = AppPrivacyRouteImport.update({
  id: '/app/privacy',
  path: '/app/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTermsRoute = AppTermsRouteImport.update({
  id: '/app/terms',
  path: '/app/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultIdRoute = ResultIdRouteImport.update({
  id: '/result/$id',
  path: '/result/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthMetadataRoute = ApiHealthMetadataRouteImport.update({
  id: '/api/health/metadata',
  path: '/api/health/metadata',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accept-terms': typeof AcceptTermsRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/debate': typeof DebateRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/leaderboard': typeof LeaderboardRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/api/debate-ai': typeof ApiDebateAiRoute
  '/api/elevenlabs-tts': typeof ApiElevenlabsTtsRoute
  '/app/contact': typeof AppContactRoute
  '/app/privacy': typeof AppPrivacyRoute
  '/app/terms': typeof AppTermsRoute
  '/result/$id': typeof ResultIdRoute
  '/api/health/metadata': typeof ApiHealthMetadataRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accept-terms': typeof AcceptTermsRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/debate': typeof DebateRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/leaderboard': typeof LeaderboardRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/api/debate-ai': typeof ApiDebateAiRoute
  '/api/elevenlabs-tts': typeof ApiElevenlabsTtsRoute
  '/app/contact': typeof AppContactRoute
  '/app/privacy': typeof AppPrivacyRoute
  '/app/terms': typeof AppTermsRoute
  '/result/$id': typeof ResultIdRoute
  '/api/health/metadata': typeof ApiHealthMetadataRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accept-terms': typeof AcceptTermsRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/debate': typeof DebateRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/leaderboard': typeof LeaderboardRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/api/debate-ai': typeof ApiDebateAiRoute
  '/api/elevenlabs-tts': typeof ApiElevenlabsTtsRoute
  '/app/contact': typeof AppContactRoute
  '/app/privacy': typeof AppPrivacyRoute
  '/app/terms': typeof AppTermsRoute
  '/result/$id': typeof ResultIdRoute
  '/api/health/metadata': typeof ApiHealthMetadataRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accept-terms'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/debate'
    | '/forgot-password'
    | '/leaderboard'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/api/debate-ai'
    | '/api/elevenlabs-tts'
    | '/app/contact'
    | '/app/privacy'
    | '/app/terms'
    | '/result/$id'
    | '/api/health/metadata'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accept-terms'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/debate'
    | '/forgot-password'
    | '/leaderboard'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/api/debate-ai'
    | '/api/elevenlabs-tts'
    | '/app/contact'
    | '/app/privacy'
    | '/app/terms'
    | '/result/$id'
    | '/api/health/metadata'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accept-terms'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/debate'
    | '/forgot-password'
    | '/leaderboard'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/api/debate-ai'
    | '/api/elevenlabs-tts'
    | '/app/contact'
    | '/app/privacy'
    | '/app/terms'
    | '/result/$id'
    | '/api/health/metadata'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcceptTermsRoute: typeof AcceptTermsRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  DebateRoute: typeof DebateRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LeaderboardRoute: typeof LeaderboardRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  ApiDebateAiRoute: typeof ApiDebateAiRoute
  ApiElevenlabsTtsRoute: typeof ApiElevenlabsTtsRoute
  AppContactRoute: typeof AppContactRoute
  AppPrivacyRoute: typeof AppPrivacyRoute
  AppTermsRoute: typeof AppTermsRoute
  ResultIdRoute: typeof ResultIdRoute
  ApiHealthMetadataRoute: typeof ApiHealthMetadataRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-terms': {
      id: '/accept-terms'
      path: '/accept-terms'
      fullPath: '/accept-terms'
      preLoaderRoute: typeof AcceptTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debate': {
      id: '/debate'
      path: '/debate'
      fullPath: '/debate'
      preLoaderRoute: typeof DebateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debate-ai': {
      id: '/api/debate-ai'
      path: '/api/debate-ai'
      fullPath: '/api/debate-ai'
      preLoaderRoute: typeof ApiDebateAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/elevenlabs-tts': {
      id: '/api/elevenlabs-tts'
      path: '/api/elevenlabs-tts'
      fullPath: '/api/elevenlabs-tts'
      preLoaderRoute: typeof ApiElevenlabsTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/contact': {
      id: '/app/contact'
      path: '/app/contact'
      fullPath: '/app/contact'
      preLoaderRoute: typeof AppContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/privacy': {
      id: '/app/privacy'
      path: '/app/privacy'
      fullPath: '/app/privacy'
      preLoaderRoute: typeof AppPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/terms': {
      id: '/app/terms'
      path: '/app/terms'
      fullPath: '/app/terms'
      preLoaderRoute: typeof AppTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/$id': {
      id: '/result/$id'
      path: '/result/$id'
      fullPath: '/result/$id'
      preLoaderRoute: typeof ResultIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health/metadata': {
      id: '/api/health/metadata'
      path: '/api/health/metadata'
      fullPath: '/api/health/metadata'
      preLoaderRoute: typeof ApiHealthMetadataRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcceptTermsRoute: AcceptTermsRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  DebateRoute: DebateRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LeaderboardRoute: LeaderboardRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  ApiDebateAiRoute: ApiDebateAiRoute,
  ApiElevenlabsTtsRoute: ApiElevenlabsTtsRoute,
  AppContactRoute: AppContactRoute,
  AppPrivacyRoute: AppPrivacyRoute,
  AppTermsRoute: AppTermsRoute,
  ResultIdRoute: ResultIdRoute,
  ApiHealthMetadataRoute: ApiHealthMetadataRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
